[package]
name = "ec-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jerasure-rs = { git = "https://github.com/Faturan/jerasure-rs" }
# jerasure-rs = { path = "../jerasure-rs" }
